-- Database population script for Quantum Adventure course content.

-- Clear existing data
DELETE FROM UserProgress;
DELETE FROM UserAchievements;
DELETE FROM Achievements;
DELETE FROM LearningUnits;
DELETE FROM CourseSections;
DELETE FROM Courses;

-- Insert Courses
INSERT INTO Courses (title, description, level) VALUES 
('Quantum Quest: The Beginner''s Journey', 'Embark on an epic adventure through the quantum realm! Perfect for curious minds ready to explore the weird and wonderful world of quantum computing.', 'Beginner'),
('Quantum Leap: Intermediate Explorations', 'Ready to dive deeper? These modules will challenge your understanding and expand your quantum toolkit.', 'Intermediate'),
('Quantum Frontiers: Advanced Expeditions', 'Push the boundaries of your knowledge. Explore cutting-edge topics and prepare to contribute to the quantum revolution.', 'Advanced');

-- Insert Beginner Course Sections
INSERT INTO CourseSections (course_id, external_id, title, icon_ref, story_intro, summary, section_order) VALUES 
((SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey'), 'introduction-to-quantum', '🚀 Quantum Awakening: What''s the Buzz?', 'RocketLaunch', 'So you''ve heard of quantum technology and how it''s going to revolutionize, well, everything. How do we know that and how does it work? Jump in here to find out!', 'Understood the revolutionary potential of quantum technology.', 0),
((SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey'), 'superposition-principles', '🌀 Superposition: The Art of Being Everywhere', 'Sparkles', 'This skill introduces the superposition principle. You''ll gain insight into where this principle comes from, why it is necessary, and what you can do with it.', 'Grasped the fundamental concept of quantum superposition.', 1),
((SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey'), 'qubits-fundamentals', '💎 Qubits: The Quantum Encoders', 'Cube', 'Start with some fundamentals in how we represent information and by the end of this skill you''ll understand how we can encode and process information using quantum physics!', 'Learned how qubits encode and process information.', 2),
((SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey'), 'measurement-in-quantum', '🔍 Measurement: The Decisive Moment', 'MagnifyingGlass', 'Measurement the destructor. What does it mean to measure something in general? What does it mean to measure something in quantum physics? Discover the dirty secrets about measurement in quantum computing.', 'Uncovered the role and impact of measurement in quantum physics.', 3);

-- Insert Intermediate Course Sections  
INSERT INTO CourseSections (course_id, external_id, title, icon_ref, story_intro, summary, section_order) VALUES 
((SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations'), 'quantum-circuits', '⚡ Quantum Circuits: Blueprints of the Quantum Realm', 'CircuitBoard', 'How do we represent the programs to be run on quantum computers? After this skill you''ll be able to decipher some of the cool diagrams you see in the field.', 'Mastered the art of reading and understanding quantum circuits.', 0),
((SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations'), 'quantum-entanglement', '🕸️ Entanglement: Spooky Action, Powerful Connections', 'LinkIcon', 'Einstein called it "spooky action at a distance." It''s not so spooky, but it may be extremely useful! Discover the most quintessential concept in quantum physics.', 'Explored the mysteries and power of quantum entanglement.', 1),
((SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations'), 'quantum-noise', '🥷 Noise: The Quantum Gremlins', 'ShieldCheck', 'Why don''t we have useful quantum computers yet? Learn what''s holding us back through an understanding of how noise and interference affect quantum computers.', 'Understood the challenges of noise in quantum computation.', 2),
((SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations'), 'quantum-control', '🎮 Quantum Control: Taming the Quantum World', 'AdjustmentsHorizontal', 'Learn all about quantum control and how it is used to create quantum gates and combat noise.', 'Learned techniques for quantum control and noise mitigation.', 3),
((SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations'), 'quantum-coding', '💻 Quantum Coding: Your First Quantum Program', 'CodeBracket', 'Ready for the real thing? Here''s your introduction to the challenges of programming a quantum computer.', 'Took the first steps into programming a quantum computer.', 4);

-- Insert Advanced Course Sections
INSERT INTO CourseSections (course_id, external_id, title, icon_ref, story_intro, summary, section_order) VALUES
((SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions'), 'advanced-algorithms-quest', '🌌 The Algorithmist''s Odyssey: Legendary Quantum Recipes', 'Scroll', 'You''ve mastered the basics, brave adventurer! Now, journey into the heart of quantum power. We''ll unearth legendary algorithms like Shor''s and Grover''s – spells that can break modern encryption and search the unsearchable. Prepare to wield computational magic!', 'Deciphered legendary quantum algorithms and their world-changing applications.', 0),
((SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions'), 'error-correction-citadel', '🛡️ Citadel of Resilience: Forging Unbreakable Qubits', 'ShieldLock', 'The quantum realm is fraught with peril – noise and decoherence threaten our delicate qubits. Enter the Citadel of Resilience, where you''ll master the advanced arts of Quantum Error Correction. Learn to build fortresses of code that protect quantum information and pave the way for fault-tolerant quantum computers!', 'Mastered advanced quantum error correction codes to protect qubits from decoherence.', 1),
((SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions'), 'quantum-ml-voyage', '🧠 Symbiosis Sagacity: The Quantum AI Convergence', 'BrainCircuit', 'Witness the dawn of a new intelligence! Embark on a voyage to where quantum mechanics and artificial intelligence converge. Explore how quantum machine learning algorithms could solve intractable problems and unlock new paradigms of thinking machines. The future of AI is quantum-woven!', 'Explored the fusion of quantum computing and AI, unlocking new intelligent frontiers.', 2),
((SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions'), 'hardware-frontiers-expedition', '🛠️ The Qubit Forgemasters: Architectures of Tomorrow', 'Chip', 'Venture into the very heart of quantum machines! This expedition takes you deep into the diverse and experimental world of quantum hardware. From superconducting loops to trapped ions and photonic pathways, discover how these marvels are engineered and the grand challenges that lie in scaling them to their full potential.', 'Journeyed through diverse quantum hardware architectures and their cutting-edge challenges.', 3),
((SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions'), 'quantum-internet-pioneers', '🌐 Weavers of the Quantum Web: The Entangled Internet', 'GlobeNetwork', 'Imagine a network bound by the very laws of quantum mechanics, offering unbreachable security and instantaneous connections. Join the pioneers weaving the Quantum Internet, a tapestry of entangled particles stretching across the globe. Explore the protocols, the promises, and the profound implications of this next-generation communication frontier.', 'Charted the course for the Quantum Internet and its revolutionary communication capabilities.', 4);

-- Learning Units for Beginner Course (Quantum Quest: The Beginner''s Journey)

-- Section: introduction-to-quantum (12 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🌟 The Quantum Spark: Welcome, Young Explorer!', 'INFO', '{"text": "Interactive story: QuantumWelcomeJourney. Embark on your quantum adventure, young explorer, and discover the spark of a new kind of magic!", "componentName": "QuantumWelcomeJourney"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎭 Classical vs Quantum: A Tale of Two Worlds', 'INFO', '{"text": "Interactive tool: WorldComparisonTool. Step into a tale of two worlds and compare the realms of classical and quantum physics.", "componentName": "WorldComparisonTool"}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '📚 The Quantum Chronicles: Historical Adventures', 'INFO', '{"text": "Journey through time to meet the quantum pioneers - Planck, Einstein, Bohr, Heisenberg, Schrödinger and their groundbreaking discoveries that opened the quantum realm."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '⚗️ Planck''s Potion Lab: The First Quantum Clue', 'INFO', '{"text": "Interactive simulation: PlanckExperimentSim. Mix potions in Planck''s lab to find the first clue that energy comes in discrete packets - quanta!", "componentName": "PlanckExperimentSim"}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎬 Einstein''s Lightbulb Moment: Photoelectric Effect', 'INFO', '{"text": "Video: /videos/photoelectric-effect-story.mp4. Witness Einstein''s brilliant insight into the photoelectric effect, revealing light as particles (photons)."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎲 Probability Palace: Understanding Quantum Chance', 'INFO', '{"text": "Interactive game: ProbabilityPalaceGame. Enter the Probability Palace and learn how quantum mechanics governs chance and uncertainty.", "componentName": "ProbabilityPalaceGame"}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🔬 The Double-Slit Detective Story', 'INFO', '{"text": "Interactive mystery: DoubleslitMystery. Become a detective and investigate the baffling behavior of particles in the double-slit experiment. Wave or particle? Or both?", "componentName": "DoubleslitMystery"}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '📱 Quantum in Your Pocket: Modern Applications', 'INFO', '{"text": "Discover how quantum effects power your smartphone, GPS, and MRI machines. The quantum world is closer than you think, enabling technologies you use every day!"}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎮 Quantum vs Classical Race: Interactive Challenge', 'CHALLENGE_PROBLEM', '{"problemStatement": "Take the Quantum vs Classical Race challenge! Pit quantum phenomena against classical intuition in this exciting game.", "hints": ["Remember superposition and entanglement for the quantum side!", "Classical physics is deterministic."], "expectedSolution": "Complete the race and identify key differences.", "componentName": "QuantumRaceGame"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🧩 The Quantum Puzzle Box: Unlocking Mysteries', 'CHALLENGE_PROBLEM', '{"problemStatement": "Dare to open the Advanced Quantum Puzzle Box? Unravel its quantum mysteries and test your understanding.", "hints": ["Think about measurement and quantum states.", "Some solutions might seem paradoxical at first."], "expectedSolution": "Successfully solve all puzzles within the box.", "componentName": "IntroQuantumPuzzleAdvanced"}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎯 Quantum Applications Treasure Hunt', 'CHALLENGE_PROBLEM', '{"problemStatement": "Embark on an exciting treasure hunt to find hidden quantum applications in everyday life and advanced technology.", "hints": ["Look for things related to lasers, medical imaging, and computing."], "expectedSolution": "Discover and list at least 7 quantum applications with brief explanations.", "componentName": "ApplicationsTreasureHunt"}', 10),
((SELECT id FROM CourseSections WHERE external_id = 'introduction-to-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🏆 Awakening Quiz: Prove Your Quantum Spark', 'QUIZ', '{"question": "Which of these is a fundamental concept in quantum mechanics that distinguishes it from classical physics?", "options": [{"text": "Energy is always continuous.", "isCorrect": false}, {"text": "Particles can exist in a superposition of multiple states simultaneously.", "isCorrect": true}, {"text": "The position and momentum of a particle can be known with perfect accuracy at the same time.", "isCorrect": false}, {"text": "All interactions are deterministic and predictable.", "isCorrect": false}], "feedbackCorrect": "Excellent! Superposition is a cornerstone of quantum mechanics, leading to its unique and powerful nature.", "feedbackIncorrect": "Not quite. Quantum mechanics introduced revolutionary ideas like quantization of energy, superposition, and inherent uncertainty. Review the core concepts!"}', 11);

-- Section: superposition-principles (13 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🌊 Wave Meet Particle: The Duality Dance', 'INFO', '{"text": "Interactive component: WaveParticleDualityExplorer"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎪 Schrödinger''s Circus: The Famous Cat Story', 'INFO', '{"text": "Enter the whimsical world of quantum superposition through the most famous thought experiment in physics. Meet the cat that is both alive AND dead!"}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🃏 The Quantum Card Trick: Multiple States Magic', 'INFO', '{"text": "Interactive component: SuperpositionCardTrick"}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '⚖️ Balance of Possibilities: Amplitude Amplitudes', 'INFO', '{"text": "Video: /videos/quantum-amplitudes.mp4"}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎯 Superposition Simulator: Create Your Own States', 'QUBIT_VISUALIZER', '{"description": "Create your own superposition states!", "initialState": {"alpha": 0.7071, "beta": 0.7071}}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🌈 The Interference Spectrum: When Waves Collide', 'INFO', '{"text": "Interactive component: InterferenceSpectrum"}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🔄 Phase Relationships: The Hidden Dance', 'INFO', '{"text": "Discover the secret choreography of quantum phases and how they determine the dance of probability."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎼 Quantum Harmonics: Music of the Spheres', 'INFO', '{"text": "Interactive component: QuantumHarmonicsGame"}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🧪 Superposition Laboratory: Hands-on Experiments', 'INFO', '{"text": "Interactive component: SuperpositionLab"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '📊 Measuring Mayhem: Collapse in Action', 'INFO', '{"text": "Video: /videos/quantum-collapse-animation.mp4"}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🌟 Superposition in Nature: Quantum Biology Adventures', 'INFO', '{"text": "Explore how nature uses quantum superposition in photosynthesis, bird navigation, and enzyme reactions."}', 10),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎮 Quantum States Quest: Interactive Adventure', 'CHALLENGE_PROBLEM', '{"problemStatement": "Embark on the Quantum States Quest! Navigate through various quantum states and identify their properties.", "hints": ["Remember superposition and entanglement."], "expectedSolution": "Successfully identify and differentiate 5 quantum states."}', 11),
((SELECT id FROM CourseSections WHERE external_id = 'superposition-principles' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🏅 Superposition Mastery Quiz: Test Your Powers', 'QUIZ', '{"question": "Which of the following best describes quantum superposition?", "options": [{"text": "A qubit is either 0 or 1.", "isCorrect": false}, {"text": "A qubit can be both 0 and 1 at the same time.", "isCorrect": true}, {"text": "A qubit is a very small classical bit.", "isCorrect": false}], "feedbackCorrect": "Correct! Superposition is a fundamental quantum property.", "feedbackIncorrect": "Not quite. Superposition allows a qubit to exist in multiple states simultaneously until measured."}', 12);

-- Section: qubits-fundamentals (14 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '💎 Birth of a Qubit: From Bit to Quantum Bit', 'INFO', '{"text": "Interactive component: BitToQubitTransformation"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🌍 The Bloch Sphere: Your Qubit''s Home Planet', 'QUBIT_VISUALIZER', '{"description": "Explore the Bloch Sphere, the home of a qubit!", "initialState": {"alpha": 1, "beta": 0}}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🧭 Navigating Qubit Space: Coordinates and States', 'INFO', '{"text": "Learn to navigate the strange geography of qubit space where every point represents a unique quantum state."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '⚡ Qubit Rotations: The Art of State Transformation', 'GATE_APPLICATION', '{"description": "Apply gates to rotate qubits on the Bloch Sphere.", "initialState": {"alpha": 1, "beta": 0}, "availableGates": ["X", "H", "Z"]}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎨 Painting with Qubits: Visualizing Quantum States', 'INFO', '{"text": "Video: /videos/qubit-visualization.mp4"}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🏗️ Qubit Constructor: Build Your Quantum Toolkit', 'CIRCUIT_BUILDER', '{"description": "Build your own quantum circuits with various gates.", "qubitCount": 2, "availableGates": ["X", "H", "Z", "CNOT"]}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🔢 Quantum Mathematics: The Language of Qubits', 'INFO', '{"text": "Dive into the mathematical foundation of qubits using complex numbers and linear algebra made simple."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎪 Multi-Qubit Circus: When Qubits Team Up', 'CIRCUIT_BUILDER', '{"description": "Explore how multiple qubits interact in a circuit.", "qubitCount": 3, "availableGates": ["X", "H", "Z", "CNOT"]}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🌡️ Physical Qubits: The Real World Implementation', 'INFO', '{"text": "Video: /videos/physical-qubits.mp4"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🔬 Qubit Quality Control: Fidelity and Coherence', 'INFO', '{"text": "Understand what makes a good qubit and the challenges of maintaining quantum information in the real world."}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎯 Qubit Target Practice: Precision State Preparation', 'CHALLENGE_PROBLEM', '{"problemStatement": "Prepare a qubit in the state |+⟩ = (1/√2)(|0⟩ + |1⟩) using available gates.", "hints": ["Start with |0⟩.", "Hadamard gate is useful here."], "expectedSolution": "Apply H gate to |0⟩."}', 10),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🧬 DNA of Quantum Computing: Qubit Encoding Schemes', 'INFO', '{"text": "Interactive component: QubitEncodingLab"}', 11),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🚀 Qubit Readout: Getting Information Out', 'INFO', '{"text": "Video: /videos/qubit-readout.mp4"}', 12),
((SELECT id FROM CourseSections WHERE external_id = 'qubits-fundamentals' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🏆 Qubit Master Challenge: The Ultimate Test', 'QUIZ', '{"question": "What is the primary function of the Bloch Sphere?", "options": [{"text": "To perform quantum computations.", "isCorrect": false}, {"text": "To visualize the state of a single qubit.", "isCorrect": true}, {"text": "To entangle multiple qubits.", "isCorrect": false}], "feedbackCorrect": "Correct! The Bloch Sphere is a geometrical representation of a single qubit''s state.", "feedbackIncorrect": "Not quite. While related to qubit states, its primary role is visualization."}', 13);

-- Section: measurement-in-quantum (12 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '👁️ The Great Observer: Introduction to Quantum Measurement', 'INFO', '{"text": "Interactive component: QuantumObserverGame"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '💥 The Collapse Chronicles: When Superposition Dies', 'INFO', '{"text": "Witness the dramatic moment when quantum possibilities become classical reality through measurement."}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎲 Quantum Dice: Understanding Probabilistic Outcomes', 'INFO', '{"text": "Interactive component: QuantumDiceSimulator"}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🔍 Measurement Laboratory: The Decisive Experiment', 'CHALLENGE_PROBLEM', '{"problemStatement": "You have a qubit in an unknown state. You can perform measurements in the Z-basis or X-basis. Devise a strategy to determine if the qubit was in the |+⟩ state or |-⟩ state.", "hints": ["Measuring in Z-basis collapses superposition.", "|+⟩ and |-⟩ are superpositions."], "expectedSolution": "Measure in X-basis. If result is 0, it was |+⟩. If 1, it was |-⟩ (assuming no noise)."}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '⚖️ Born''s Rule: The Law of Quantum Probability', 'INFO', '{"text": "Video: /videos/borns-rule-explained.mp4"}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎯 Measurement Basis: Choosing Your Quantum Lens', 'INFO', '{"text": "Interactive component: MeasurementBasisExplorer"}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🌊 The Uncertainty Tsunami: Heisenberg''s Principle', 'INFO', '{"text": "Explore the fundamental limits of what we can know about quantum systems simultaneously."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🎪 Quantum Nondemolition: Measuring Without Destroying', 'INFO', '{"text": "Interactive component: QNDMeasurementSim"}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🛡️ The Observer Effect Shield: Protecting Quantum States', 'INFO', '{"text": "Learn strategies to minimize the impact of measurement on quantum systems."}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🌌 Beyond the Veil: Advanced Measurement Techniques', 'INFO', '{"text": "Video: /videos/advanced-measurement.mp4"}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🕹️ Quantum Measurement Challenge: Test Your Skills', 'CHALLENGE_PROBLEM', '{"problemStatement": "Design an experiment to distinguish between the states |0⟩ and |+⟩ with a single measurement.", "hints": ["Think about different measurement bases."], "expectedSolution": "Measure in the X-basis. |0⟩ will give 50/50 0 or 1. |+⟩ will give 0 with 100% probability."}', 10),
((SELECT id FROM CourseSections WHERE external_id = 'measurement-in-quantum' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Quest: The Beginner''s Journey')), '🏆 Measurement Master Quiz: The Final Verdict', 'QUIZ', '{"question": "What happens to a qubit''s superposition when it is measured?", "options": [{"text": "It remains in superposition.", "isCorrect": false}, {"text": "It collapses to a definite state (0 or 1).", "isCorrect": true}, {"text": "It becomes entangled with another qubit.", "isCorrect": false}], "feedbackCorrect": "Correct! Measurement forces the qubit out of superposition into a classical state.", "feedbackIncorrect": "Incorrect. Measurement is a disruptive process that collapses superposition."}', 11);

-- Learning Units for Intermediate Course (Quantum Leap: Intermediate Explorations - course_id 2)

-- Section: quantum-circuits (12 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '📜 Circuit Scrolls: Reading Quantum Notation', 'INFO', '{"text": "Interactive component: CircuitNotationGuide"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🧱 Basic Building Blocks: Single-Qubit Gates', 'GATE_APPLICATION', '{"description": "Explore common single-qubit gates like X, Y, Z, H, S, T.", "initialState": {"alpha": 1, "beta": 0}, "availableGates": ["X", "Y", "Z", "H", "S", "T"]}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🔗 Linking Qubits: The CNOT Connection', 'CIRCUIT_BUILDER', '{"description": "Understand the CNOT gate and its role in entanglement.", "qubitCount": 2, "availableGates": ["H", "X", "CNOT"]}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🛠️ Circuit Constructor: Your First Quantum Programs', 'CIRCUIT_BUILDER', '{"description": "Build simple quantum circuits to achieve specific state transformations.", "qubitCount": 2, "availableGates": ["H", "X", "Z", "CNOT"]}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🌀 Universal Gate Sets: The Quantum Toolkit', 'INFO', '{"text": "Video: /videos/universal-gate-sets.mp4"}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '📐 Measuring Outcomes: Extracting Information from Circuits', 'CIRCUIT_BUILDER', '{"description": "Add measurement operations to your circuits and observe outcomes.", "qubitCount": 2, "availableGates": ["H", "X", "CNOT", "MEASURE"]}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🧩 Circuit Puzzles: Logic Gate Challenges', 'CHALLENGE_PROBLEM', '{"problemStatement": "Construct a circuit to swap the states of two qubits using only CNOT and H gates.", "hints": ["Think about how CNOT can be used to copy information under certain conditions.", "Three CNOTs are involved."], "expectedSolution": "CNOT(0,1), CNOT(1,0), CNOT(0,1) sequence."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🎭 No-Cloning Theorem: The Uncopyable Qubit', 'INFO', '{"text": "Interactive demonstration: NoCloningTheoremDemo"}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '얽힘 Entanglement Creation: The Bell State Circuit', 'CIRCUIT_BUILDER', '{"description": "Build the famous Bell state circuit (Hadamard on qubit 0, then CNOT(0,1)). Observe the entangled output.", "qubitCount": 2, "availableGates": ["H", "X", "CNOT", "MEASURE"]}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '텔레포트 Quantum Teleportation: Sending Qubit States (Conceptual)', 'INFO', '{"text": "Explore the mind-bending concept of quantum teleportation and the circuit that makes it possible (conceptual overview)."}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '📖 Circuit Library: Common Quantum Algorithms Snippets', 'INFO', '{"text": "Browse a library of small, famous quantum circuit snippets like Deutsch-Jozsa (2-qubit) or Grover search (2-qubit)."}', 10),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-circuits' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🏆 Circuit Architect Quiz: Test Your Design Skills', 'QUIZ', '{"question": "Which gate is crucial for creating entanglement between two qubits?", "options": [{"text": "Hadamard (H)", "isCorrect": false}, {"text": "Pauli-X (X)", "isCorrect": false}, {"text": "CNOT", "isCorrect": true}], "feedbackCorrect": "Correct! The CNOT gate is essential for creating entangled Bell states.", "feedbackIncorrect": "Not quite. While H creates superposition, CNOT is needed to entangle two qubits."}', 11);

-- Section: quantum-entanglement (11 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🤝 The Quantum Handshake: Introduction to Entanglement', 'INFO', '{"text": "Interactive story: EntanglementIntroduction"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🔔 Bell States: The VIPs of Entanglement', 'BELL_STATE_EXPLORER', '{"description": "Explore the four Bell states and their properties."}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '👻 Spooky Action at a Distance: Einstein''s Puzzle', 'INFO', '{"text": "Video: /videos/epr-paradox.mp4"}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🎲 Correlated Destinies: Measuring Entangled Qubits', 'CIRCUIT_BUILDER', '{"description": "Create a Bell state, then measure both qubits in different bases. Observe the correlations.", "qubitCount": 2, "availableGates": ["H", "X", "CNOT", "MEASURE"]}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🔐 Quantum Cryptography: The Unbreakable Code (BB84 Intro)', 'INFO', '{"text": "Learn how entanglement forms the basis of secure quantum communication (conceptual overview of BB84)."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '⛓️ Entanglement Swapping: Connecting Distant Qubits', 'INFO', '{"text": "Interactive simulation: EntanglementSwappingSim"}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🔬 Experimental Entanglement: How It''s Done in Labs', 'INFO', '{"text": "Video: /videos/lab-entanglement.mp4"}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '얽힘 Entanglement in Nature: From Molecules to Stars', 'INFO', '{"text": "Discover examples of entanglement beyond the lab, in natural processes."}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🎮 Entanglement Challenge: The CHSH Game', 'CHALLENGE_PROBLEM', '{"problemStatement": "Play the CHSH game to witness a violation of local realism, proving the non-local nature of entanglement.", "hints": ["You and your partner (simulated) will receive entangled particles.", "Choose your measurement settings wisely."], "expectedSolution": "Achieve a score that violates Bell''s inequality.", "componentName": "CHSHGame"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '💭 The Philosophy of Entanglement: What Does It Mean?', 'REFLECTION_PROMPT', '{"prompt": "After learning about entanglement, what are your thoughts on its implications for our understanding of reality?"}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-entanglement' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🏆 Entanglement Expert Quiz: Unravel the Mystery', 'QUIZ', '{"question": "What is a key characteristic of entangled particles?", "options": [{"text": "They are always in the same state.", "isCorrect": false}, {"text": "Their fates are correlated, no matter how far apart they are.", "isCorrect": true}, {"text": "They can travel faster than light.", "isCorrect": false}], "feedbackCorrect": "Exactly! Entangled particles exhibit correlations that classical physics cannot explain.", "feedbackIncorrect": "Not quite. Entanglement implies a deep connection and correlated outcomes upon measurement."}', 10);

-- Section: quantum-noise (10 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🤫 The Sound of Silence (is Golden): Intro to Quantum Noise', 'INFO', '{"text": "Interactive story: NoiseGremlins"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '📉 Decoherence Dragon: When Quantumness Fades', 'INFO', '{"text": "Video: /videos/decoherence-explained.mp4"}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🌡️ Thermal Tremors: Environmental Noise Sources', 'INFO', '{"text": "Learn how heat and other environmental factors can corrupt quantum information."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '💥 Gate Glitches: Imperfect Quantum Operations', 'GATE_APPLICATION', '{"description": "Simulate the effect of common noise channels (e.g., bit-flip, phase-flip) on qubit states after gate applications.", "initialState": {"alpha": 0.7071, "beta": 0.7071}, "availableGates": ["X", "H"], "noiseModels": ["bitFlip", "phaseFlip"]}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🛡️ Quantum Armor: Introduction to Error Mitigation', 'INFO', '{"text": "Discover the first line of defense against quantum noise – error mitigation techniques."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '⚖️ Fidelity Fortress: Measuring Quantum State Purity', 'INFO', '{"text": "Interactive tool: FidelityCalculator. Understand how we quantify the ''goodness'' of a quantum state in the presence of noise.", "componentName": "FidelityCalculator"}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '⚙️ Gate Glitches: Imperfect Quantum Operations', 'INFO', '{"text": "No quantum gate is perfect. Learn about gate errors and how they accumulate during a computation."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '📉 Noise Navigator: Charting Noise Characteristics', 'CHALLENGE_PROBLEM', '{"problemStatement": "Given a noisy quantum channel, use tomography techniques to estimate the primary type of noise affecting the qubits.", "hints": ["Consider Pauli error channels.", "Repeated measurements can reveal error probabilities."], "expectedSolution": "Identify the dominant noise channel (e.g., bit-flip, phase-flip, or depolarizing) and estimate its strength.", "componentName": "NoiseTomographyChallenge"}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🛠️ Mitigation Masterclass: Applying Basic Correction', 'CIRCUIT_BUILDER', '{"description": "Implement a simple error mitigation scheme (e.g., repetition code for bit-flips) on a noisy qubit.", "qubitCount": 3, "availableGates": ["X", "H", "CNOT", "Measure"], "noiseModel": {"bitFlipProbability": 0.05}}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🌍 Environmental Echoes: Shielding from the Outside World', 'INFO', '{"text": "Explore advanced shielding techniques and cryogenics used to protect qubits from environmental noise."}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🧩 Noise Puzzle Challenge: Beat the Gremlins', 'CHALLENGE_PROBLEM', '{"problemStatement": "A quantum circuit is producing incorrect results due to a specific type of noise. Identify the noise and modify the circuit to compensate.", "hints": ["Look for systematic errors in output probabilities.", "Sometimes adding specific gates can cancel out noise effects."], "expectedSolution": "A modified circuit that produces the correct output despite the noise.", "componentName": "NoisePuzzleAdvanced"}', 10),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-noise' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🏆 Noise Ninja Quiz: Test Your Shielding Skills', 'QUIZ', '{"question": "What is the primary effect of decoherence on a qubit?", "options": [{"text": "It flips the qubit''s state from |0⟩ to |1⟩.", "isCorrect": false}, {"text": "It causes the qubit to lose its quantum properties and behave classically.", "isCorrect": true}, {"text": "It entangles the qubit with all other qubits in the system.", "isCorrect": false}, {"text": "It increases the qubit''s energy.", "isCorrect": false}], "feedbackCorrect": "Correct! Decoherence is the loss of quantum coherence, leading to classical behavior.", "feedbackIncorrect": "Not quite. Decoherence is a fundamental challenge where a qubit loses its quantum nature due to interaction with its environment."}', 11);

-- Section: quantum-control (12 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🕹️ The Quantum Puppeteer: Introduction to Control', 'INFO', '{"text": "Interactive story: QuantumControlIntro"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '💡 Laser Precision: Controlling Qubits with Light', 'INFO', '{"text": "Video: /videos/laser-qubit-control.mp4. Learn how lasers are used to manipulate trapped ion and neutral atom qubits."}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '⚡ Microwave Mastery: Guiding Superconducting Qubits', 'INFO', '{"text": "Explore how microwave pulses are used to perform gates on superconducting qubits."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🔄 Pulse Shaping Studio: Designing Quantum Gates', 'GATE_APPLICATION', '{"description": "Interactive: PulseShaper. Experiment with pulse parameters (amplitude, duration, phase) to see how they affect qubit rotations (conceptual).", "componentName": "PulseShaper"}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🎯 Optimal Control Theory: Finding the Perfect Pulse', 'INFO', '{"text": "An overview of how algorithms can design complex control sequences for high-fidelity quantum operations."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🔊 Dynamical Decoupling Dance: Fighting Noise with Control', 'INFO', '{"text": "Interactive simulation: DynamicalDecouplingSim. See how carefully timed control pulses can ''refocus'' qubits and mitigate certain types of noise.", "componentName": "DynamicalDecouplingSim"}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🛠️ Calibration Station: Keeping Qubits in Tune', 'INFO', '{"text": "Understand the constant need for calibration in quantum hardware to maintain gate fidelity."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🎮 Control Challenge: The Qubit Stabilizer', 'CHALLENGE_PROBLEM', '{"problemStatement": "A qubit is drifting due to a known, slow phase error. Design a simple periodic control sequence (e.g., using Z gates) to counteract this drift.", "hints": ["Think about how a Z gate affects the phase.", "Timing is key."], "expectedSolution": "Apply Z gates at appropriate intervals to reverse the phase accumulation."}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '💭 The Art of Control: Reflection', 'REFLECTION_PROMPT', '{"prompt": "Quantum control seems like a delicate dance. What aspect of it do you find most fascinating or challenging?"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-control' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🏆 Control Virtuoso Quiz: Master the Quantum Realm', 'QUIZ', '{"question": "What is a primary goal of quantum control?", "options": [{"text": "To make qubits bigger.", "isCorrect": false}, {"text": "To perform high-fidelity quantum operations and mitigate noise.", "isCorrect": true}, {"text": "To cool qubits to absolute zero.", "isCorrect": false}], "feedbackCorrect": "Precisely! Quantum control is about accurately manipulating qubits and protecting them from errors.", "feedbackIncorrect": "Not quite. Quantum control focuses on the precise execution of quantum gates and noise reduction."}', 9);

-- Section: quantum-coding (10 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '⌨️ Code Commander: Your First Quantum Program', 'INFO', '{"text": "Interactive tutorial: QuantumCodingSetup. Set up a simple quantum coding environment (e.g., using a web-based simulator with a Python-like SDK).", "componentName": "QuantumCodingSetup"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🐍 Qiskit Quickstart / Cirq Primer (Conceptual)', 'INFO', '{"text": "A brief introduction to the syntax and basic operations of a popular quantum SDK like Qiskit or Cirq (focus on concepts, not deep dives)."}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🛠️ Building Bell: Coding an Entangled State', 'CODE_CHALLENGE', '{"problemStatement": "Write code using a quantum SDK to create a Bell state (|Φ+⟩) between two qubits and measure them.", "language": "qiskit", "scaffoldCode": "from qiskit import QuantumCircuit, transpile, assemble, Aer, visualization\n# Create a quantum circuit with 2 qubits and 2 classical bits\nqc = QuantumCircuit(2, 2)\n# Apply gates here\n# ... \n# Measure qubits\nqc.measure([0,1], [0,1])\n# Simulate and get counts\n...", "hints": ["Use H gate on the first qubit.", "Use CNOT gate with control q0 and target q1."], "expectedOutput": "Counts showing roughly 50% ''00'' and 50% ''11''."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '➕ Quantum Adder: A Simple Arithmetic Circuit', 'CODE_CHALLENGE', '{"problemStatement": "Implement a quantum circuit that acts as a half-adder (adds two single bits, producing a sum and a carry bit).", "language": "qiskit", "scaffoldCode": "# ... imports ...\nqc = QuantumCircuit(3, 2) # 2 input qubits, 1 ancilla for carry, 2 classical bits for sum & carry\n# Initialize input qubits if needed (e.g., to |1⟩)\n# ... your adder logic ...\nqc.measure([?,?], [0,1]) # Measure sum and carry qubits\n# ... simulation ...", "hints": ["You''ll need CNOT and Toffoli (CCX) gates.", "The sum can be q0 XOR q1. The carry is q0 AND q1."], "expectedOutput": "Correct sum and carry bits for inputs like 00, 01, 10, 11."}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🔄 Running on Simulators vs. Real Hardware (Conceptual)', 'INFO', '{"text": "Understand the differences, pros, and cons of running quantum code on simulators versus actual quantum devices (noise, queue times, access)."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '📊 Interpreting Results: Histograms and Statevectors', 'INFO', '{"text": "Learn how to read measurement outcome histograms and (for simulators) how to access the underlying quantum statevector."}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🐛 Debugging Quantum Code: It''s Not Always Obvious!', 'INFO', '{"text": "Discuss common pitfalls and strategies for debugging quantum programs, where direct inspection of intermediate states is often impossible."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🚀 Grover''s Search (2-qubit): Find the Marked Item', 'CODE_CHALLENGE', '{"problemStatement": "Implement Grover''s algorithm for a 2-qubit search space to find one marked item (e.g., state |11⟩).", "language": "qiskit", "scaffoldCode": "# ... imports ...\nqc = QuantumCircuit(2, 2)\n# Oracle for marked item |11⟩ (e.g., controlled-Z gate)\n# ... \n# Grover diffusion operator (Hadamards, X-gates, controlled-Z, X-gates, Hadamards)\n# ... \nqc.measure([0,1], [0,1])\n# ... simulation ...", "hints": ["The oracle flips the phase of the marked item.", "The diffusion operator amplifies the amplitude of the marked item."], "expectedOutput": "High probability of measuring the marked item."}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '💭 My Quantum Coding Journey: Reflection', 'REFLECTION_PROMPT', '{"prompt": "What was the most surprising or challenging part of writing your first few quantum programs?"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-coding' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Leap: Intermediate Explorations')), '🏆 Quantum Coder Certification (Basic): Pass the Test!', 'QUIZ', '{"question": "In Qiskit, what is the typical first step in creating a quantum program?", "options": [{"text": "Defining the noise model.", "isCorrect": false}, {"text": "Creating a QuantumCircuit object.", "isCorrect": true}, {"text": "Choosing the backend hardware.", "isCorrect": false}], "feedbackCorrect": "Correct! You usually start by defining your QuantumCircuit.", "feedbackIncorrect": "While important, defining the circuit itself is the primary first step."}', 9);

-- Learning Units for Advanced Course (Quantum Frontiers: Advanced Expeditions - course_id 3)

-- Section: advanced-algorithms-quest (12 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '📜 The Algorithmist''s Oath: Beyond Basic Circuits', 'INFO', '{"text": "Welcome, Algorithmist! Prepare to delve into quantum algorithms that promise exponential speedups."}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔑 Shor''s Algorithm: The Codebreaker''s Dream (Part 1: Overview)', 'INFO', '{"text": "Video: /videos/shors-algorithm-overview.mp4. Understand the structure and potential impact of Shor''s algorithm for factoring."}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔢 Shor''s Algorithm: The Quantum Fourier Transform (Part 2: QFT Deep Dive)', 'CIRCUIT_BUILDER', '{"description": "Explore the Quantum Fourier Transform (QFT) circuit, a key component of Shor''s. Implement a 3-qubit QFT.", "qubitCount": 3, "availableGates": ["H", "CPHASE", "SWAP"]}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '⏳ Shor''s Algorithm: Period Finding & Factoring (Part 3: The Finale)', 'INFO', '{"text": "Interactive simulation: ShorsPeriodFindingSim. See how period finding (the quantum part) leads to factoring (the classical post-processing).", "componentName": "ShorsPeriodFindingSim"}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔍 Grover''s Algorithm Revisited: Scaling the Search', 'CODE_CHALLENGE', '{"problemStatement": "Implement Grover''s algorithm for a 3-qubit search space (N=8 items). Design the oracle for a specific marked item.", "language": "qiskit", "hints": ["The oracle needs to be more complex for 3 qubits (e.g., multi-controlled Z or equivalent).", "The number of Grover iterations is approx. sqrt(N)."], "expectedOutput": "High probability of measuring the marked 3-qubit state."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💡 Quantum Phase Estimation: Unveiling Eigenvalues', 'INFO', '{"text": "Understand the Quantum Phase Estimation (QPE) algorithm and its use in other algorithms like Shor''s."}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '⚛️ Simulating Molecules: Variational Quantum Eigensolver (VQE)', 'INFO', '{"text": "Introduction to VQE, a hybrid quantum-classical algorithm for finding ground state energies of molecules. Conceptual overview."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '📈 Optimization with QAOA: Quantum Approximate Optimization Algorithm', 'INFO', '{"text": "Overview of QAOA for solving combinatorial optimization problems. Conceptual."}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🚶 Quantum Walks: A Quantum Leap in Random Walks', 'INFO', '{"text": "Interactive simulation: QuantumWalkSim. Compare classical random walks with quantum walks and their faster spreading.", "componentName": "QuantumWalkSim"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '📚 The Quantum Algorithm Zoo: Exploring Further', 'INFO', '{"text": "Brief mentions of other algorithms like HHL (solving linear systems), Quantum Amplitude Amplification/Estimation."}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💭 Algorithm Architect Reflection: The Power and Limits', 'REFLECTION_PROMPT', '{"prompt": "Which quantum algorithm do you find most impactful or intriguing, and what challenges do you foresee in its practical implementation?"}', 10),
((SELECT id FROM CourseSections WHERE external_id = 'advanced-algorithms-quest' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🏆 Algorithm Grandmaster Quiz: Legendary Knowledge Test', 'QUIZ', '{"question": "Shor''s algorithm provides an exponential speedup for which problem?", "options": [{"text": "Unsorted database search.", "isCorrect": false}, {"text": "Factoring large numbers.", "isCorrect": true}, {"text": "Protein folding.", "isCorrect": false}], "feedbackCorrect": "Correct! Shor''s algorithm''s ability to factor large numbers threatens classical encryption.", "feedbackIncorrect": "While Grover''s algorithm helps with search, Shor''s is famous for factoring."}', 11);

-- Section: error-correction-citadel (11 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🛡️ The Imperfect Qubit: Why We Need Error Correction', 'INFO', '{"text": "Recap of noise and decoherence. The necessity of QEC for fault-tolerant quantum computation."}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🧱 Classical Repetition Code: The Simple Start', 'INFO', '{"text": "Understanding classical error correction with repetition codes as an analogy."}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🚫 No-Cloning Conundrum: The Quantum Challenge', 'INFO', '{"text": "Why classical repetition codes don''t directly work for quantum information due to the no-cloning theorem and measurement disturbance."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔧 The 3-Qubit Bit-Flip Code: A Quantum Repetition', 'CIRCUIT_BUILDER', '{"description": "Implement the 3-qubit bit-flip code: encode a logical qubit, simulate a bit-flip error on one physical qubit, and decode to recover the state.", "qubitCount": 3, "ancillaCount": 2}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔄 The 3-Qubit Phase-Flip Code: Handling Phase Errors', 'CIRCUIT_BUILDER', '{"description": "Implement the 3-qubit phase-flip code. Similar to the bit-flip code but uses a Hadamard basis transformation.", "qubitCount": 3, "ancillaCount": 2}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🌟 Shor''s 9-Qubit Code: Tackling Both Bit and Phase Flips', 'INFO', '{"text": "Conceptual overview of the Shor code, the first full quantum error correcting code."}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '📐 Stabilizer Codes: The Power of Commuting Operators', 'INFO', '{"text": "Introduction to the stabilizer formalism, a powerful mathematical framework for constructing and understanding QEC codes (e.g., the 5-qubit code)."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🗺️ Surface Codes & Topological Codes: The Path to Scalability', 'INFO', '{"text": "Video: /videos/surface-codes.mp4. Understanding surface codes, a leading candidate for fault-tolerant quantum computers, and their high error thresholds."}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🚧 The Threshold Theorem: Hope for Fault-Tolerance', 'INFO', '{"text": "Explanation of the threshold theorem: if physical error rates are below a certain threshold, arbitrarily long quantum computations can be performed reliably."}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💭 Architect of Resilience: QEC Reflections', 'REFLECTION_PROMPT', '{"prompt": "Quantum error correction is a complex but vital field. What aspect of QEC do you find most ingenious or challenging to grasp?"}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'error-correction-citadel' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🏆 QEC Guardian Quiz: Test Your Protective Spells', 'QUIZ', '{"question": "What is a key principle of quantum error correction that differs from classical error correction?", "options": [{"text": "Copying the quantum state multiple times.", "isCorrect": false}, {"text": "Using entanglement and syndrome measurements without collapsing the logical state.", "isCorrect": true}, {"text": "Making qubits colder to reduce errors.", "isCorrect": false}], "feedbackCorrect": "Correct! QEC uses clever entanglement and syndrome measurements to detect errors without destroying the encoded information.", "feedbackIncorrect": "A key difference is that QEC cannot simply copy states due to the no-cloning theorem. It uses more sophisticated methods."}', 10);

-- Section: quantum-ml-voyage (10 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🤖 The Thinking Quantum Machine: Intro to QML', 'INFO', '{"text": "Exploring the intersection of quantum computing and machine learning. What unique capabilities can quantum bring to AI?"}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '📈 Quantum-Enhanced Data Encoding: Feature Maps', 'INFO', '{"text": "How classical data can be encoded into quantum states for processing by quantum algorithms (e.g., amplitude encoding, angle encoding)."}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🧠 Quantum Kernels & Support Vector Machines (QSVM)', 'INFO', '{"text": "Conceptual overview of how quantum feature maps can define powerful kernels for SVMs, potentially offering advantages in classification tasks."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '📉 Variational Quantum Classifiers (VQC)', 'CODE_CHALLENGE', '{"problemStatement": "Implement a simple VQC using a parameterized quantum circuit to classify a toy dataset (e.g., two concentric circles).", "language": "qiskit_machine_learning", "hints": ["Use a feature map to encode data.", "Create an ansatz (parameterized circuit).", "Optimize parameters using a classical optimizer to minimize a loss function."], "expectedOutput": "A trained VQC that can classify new data points with reasonable accuracy."}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🌌 Quantum Neural Networks (QNNs): Architectures & Possibilities', 'INFO', '{"text": "Exploring different models for QNNs and their potential applications, from image recognition to drug discovery."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔄 Quantum Generative Adversarial Networks (QGANs)', 'INFO', '{"text": "Video: /videos/qgans.mp4. How QGANs could generate complex data distributions, potentially outperforming classical GANs in some scenarios."}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '⚡ Speedups in QML: Where''s the Quantum Advantage?', 'INFO', '{"text": "Discussion on potential sources of quantum advantage in ML (e.g., faster linear algebra, exploring vast feature spaces) and the ongoing research to prove it."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🚧 Challenges in QML: Data Loading, Barren Plateaus, Noise', 'INFO', '{"text": "Understanding the hurdles in practical QML, including the data input/output problem, barren plateaus in training, and the impact of noise."}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💭 The Future of Intelligence: QML Reflections', 'REFLECTION_PROMPT', '{"prompt": "What potential application of Quantum Machine Learning excites you the most, and what do you see as its biggest societal impact?"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-ml-voyage' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🏆 QML Visionary Quiz: Test Your Foresight', 'QUIZ', '{"question": "What is a potential advantage of using quantum kernels in SVMs?", "options": [{"text": "They always run faster than classical kernels.", "isCorrect": false}, {"text": "They can access and process information in exponentially large quantum feature spaces.", "isCorrect": true}, {"text": " They require less data to train.", "isCorrect": false}], "feedbackCorrect": "Correct! Quantum kernels can map classical data to high-dimensional Hilbert spaces, potentially finding patterns classical kernels might miss.", "feedbackIncorrect": "While speedups are hoped for, the primary advantage of quantum kernels lies in their ability to work with richer feature spaces."}', 9);

-- Section: hardware-frontiers-expedition (11 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🛠️ The Qubit Crafters: Journey into Quantum Hardware', 'INFO', '{"text": "An overview of the diverse physical systems being explored to build qubits."}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '❄️ Superconducting Circuits: The Cool Contenders', 'INFO', '{"text": "Deep dive into superconducting qubits (transmons, fluxoniums): principles, fabrication, pros, and cons. Video: /videos/superconducting-qubits.mp4"}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '✨ Trapped Ions: Precision Performers', 'INFO', '{"text": "Exploring trapped ion qubits: how ions are held and manipulated with lasers, high fidelities, challenges in scaling."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '⚛️ Neutral Atoms: The Scalable Swarms', 'INFO', '{"text": "Understanding neutral atom qubits in optical lattices or tweezers: Rydberg interactions, potential for large qubit numbers."}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💡 Photonic Qubits: Messengers of Light', 'INFO', '{"text": "How photons can be used as qubits (e.g., polarization, path encoding), linear optical quantum computing (LOQC), challenges in creating deterministic gates."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💎 Diamond NV Centers: Solid-State Sentinels', 'INFO', '{"text": "Nitrogen-Vacancy (NV) centers in diamond: spin qubits with good coherence, potential for quantum sensing and networks."}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🌀 Topological Qubits: The Elusive Protectors (Conceptual)', 'INFO', '{"text": "Introduction to the concept of topological qubits (e.g., Majorana fermions) and their promise of built-in error protection. Highly experimental."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '⚖️ Comparing Architectures: The Qubit Scorecard', 'INFO', '{"text": "A comparative look at different qubit modalities based on criteria like coherence, gate fidelity, connectivity, scalability, and manufacturability."}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔗 The Connectivity Challenge: How Qubits Talk', 'INFO', '{"text": "Understanding the importance of qubit connectivity (e.g., all-to-all vs. nearest-neighbor) and its impact on algorithm implementation."}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💭 The Hardware Horizon: Reflections on Building Quantum', 'REFLECTION_PROMPT', '{"prompt": "Which quantum hardware approach do you find most promising for achieving large-scale, fault-tolerant quantum computation, and why?"}', 9),
((SELECT id FROM CourseSections WHERE external_id = 'hardware-frontiers-expedition' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🏆 Hardware Architect Quiz: Know Your Qubits', 'QUIZ', '{"question": "Which of these qubit types typically requires extremely low temperatures (milli-Kelvin range) to operate?", "options": [{"text": "Trapped Ions", "isCorrect": false}, {"text": "Superconducting Qubits", "isCorrect": true}, {"text": "Photonic Qubits", "isCorrect": false}], "feedbackCorrect": "Correct! Superconducting qubits need cryogenic temperatures to maintain their quantum properties.", "feedbackIncorrect": "While many qubit types benefit from cooling, superconducting qubits are known for requiring ultra-low temperatures."}', 10);

-- Section: quantum-internet-pioneers (10 units)
INSERT INTO LearningUnits (section_id, title, unit_type, unit_data, unit_order) VALUES
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🌐 Weaving the Quantum Web: Vision of the Quantum Internet', 'INFO', '{"text": "What is the Quantum Internet? Potential applications beyond classical internet: secure communication, distributed quantum computing, enhanced sensing."}', 0),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔑 Quantum Key Distribution (QKD): Unconditionally Secure Communication', 'INFO', '{"text": "Deep dive into QKD protocols (e.g., BB84, E91) and how they leverage quantum mechanics for provably secure key exchange. Video: /videos/qkd-explained.mp4"}', 1),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🔗 Quantum Repeaters: Overcoming Distance Limitations', 'INFO', '{"text": "The challenge of photon loss in optical fibers and how quantum repeaters (using entanglement swapping and purification) aim to extend the range of quantum communication."}', 2),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🛰️ Satellite QKD: Quantum Links from Space', 'INFO', '{"text": "Using satellites to establish intercontinental QKD links, overcoming limitations of ground-based fiber networks."}', 3),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🤝 Entanglement Distribution Networks: Sharing Spooky Action', 'INFO', '{"text": "Designing networks to distribute entangled pairs between users for various quantum communication protocols."}', 4),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💻 Distributed Quantum Computing: Linking Quantum Processors', 'INFO', '{"text": "The vision of connecting multiple smaller quantum computers to perform computations beyond the capability of any single device."}', 5),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🌍 The Quantum Network Stack: Protocols and Architectures', 'INFO', '{"text": "Conceptual overview of the layers and protocols needed for a functional quantum internet, analogous to the classical OSI model."}', 6),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🚧 Challenges and Roadmap: Building the Quantum Internet', 'INFO', '{"text": "Current state of quantum network development, major technical hurdles (e.g., quantum memory, repeater efficiency), and future outlook."}', 7),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '💭 The Entangled Future: Quantum Internet Reflections', 'REFLECTION_PROMPT', '{"prompt": "What application of the Quantum Internet do you believe will have the most profound impact on society?"}', 8),
((SELECT id FROM CourseSections WHERE external_id = 'quantum-internet-pioneers' AND course_id = (SELECT id FROM Courses WHERE title = 'Quantum Frontiers: Advanced Expeditions')), '🏆 Quantum Network Architect Quiz: Design the Future Web', 'QUIZ', '{"question": "What is a primary challenge in building a large-scale quantum internet?", "options": [{"text": "Generating enough classical bits to control it.", "isCorrect": false}, {"text": "Maintaining entanglement over long distances and through repeaters.", "isCorrect": true}, {"text": "Finding enough fiber optic cable.", "isCorrect": false}], "feedbackCorrect": "Correct! Long-distance entanglement and quantum repeaters are key hurdles.", "feedbackIncorrect": "While resources are a concern, the fundamental quantum challenge lies in preserving delicate entangled states over distance."}', 9);
