# Cloudflare Workers configuration for Quantum Adventure

name = "quantum-adventure"
main = "functions/_worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "quantum-adventure-db"
database_id = "8f89ce8c-cbbc-4c96-b092-3a2e9b937965"

# KV storage for OpenAuth
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "oauth_kv_namespace"
preview_id = "oauth_kv_preview"

# Environment variables for development
[vars]
APP_BASE_URL = "http://localhost:8787"
JWT_SECRET = "development-secret-key"

# OAuth provider credentials (set these as secrets in production)
# GOOGLE_CLIENT_ID = "your-google-client-id"
# GOOGLE_CLIENT_SECRET = "your-google-client-secret"
# FACEBOOK_CLIENT_ID = "your-facebook-client-id"
# FACEBOOK_CLIENT_SECRET = "your-facebook-client-secret"
# GITHUB_CLIENT_ID = "your-github-client-id"
# GITHUB_CLIENT_SECRET = "your-github-client-secret"

# Development configuration
[dev]
port = 8787
local_protocol = "http"
